### DISCUSSION TITLE
Low wattage reading on L1.  L2 reads properly

### DISCUSSION THREAD

**Discussion by kdrummer** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#122] [Q&A]
I'm bewildered here and need a sanity check.  My split phase readings on L2 are correct, but my L1 wattage reading is 85% lower than what I would expect!  

- Both CTs on L2 read properly
- Both CTs on L1 read low wattage, yet agree with each other
- Verified current and voltage calibration on both CTs with multimeter (clamp + probe)
- Reversing the L1 CT yields a negative wattage, so it should be on the correct way

Can I get a fresh pair of eyes or a new perspective on this?  I'm not sure how I can correctly measure Volts & Amps, but get the wattage wrong only on L1.  Any insights as to what I'm missing would be greatly appreciated!

Side issue:  My readings for my AFCI breakers are all over the place.  Do those possibly phase shift the voltage enough to throw off the reading?

<img width="383" alt="Low Wattage Reading" src="https://user-images.githubusercontent.com/7503408/207787976-7b4f770b-2868-46d2-9485-ee8a08983bd3.png">

![IMG_2813](https://user-images.githubusercontent.com/7503408/207783583-8c9612c2-0a55-4aa2-92de-9265f40cb931.jpeg)

Including the truncated code below in case it's relevant.
```
substitutions:
  disp_name: Energy_Monitor
  short_name: EM
  update_time: 10s
  current_cal: '11143'
  current_cal_sct006: '11143'
  current_cal_sct010: '41660'
  current_cal_sct024: '27518'
  voltage_cal: '7305'

sensor:
#IC1 Main-A
  - platform: atm90e32
    cs_pin: 5
    #CT 1
    phase_a:
      voltage:
        name: ${short_name} L1 Volts
        id: L1Volts
        accuracy_decimals: 1
      current:
        name: ${short_name} L1 Amps
        id: L1Amps
      power:
        name: ${short_name} L1 Watts 
        id: L1Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal_sct024}

    ...<truncated>...

#IC2 Main-B
  - platform: atm90e32
    cs_pin: 4

    ...<truncated>...

    #CT 6
    phase_c:
      voltage:
        name: ${short_name} L2 Volts
        id: L2Volts
        accuracy_decimals: 1
      current:
        name: ${short_name} L2 Amps 
        id: L2Amps
      power:
        name: ${short_name} L2 Watts 
        id: L2Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal_sct024}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}

#Total Watts Main.  Actual measurement from L1/L2.  Other values are measured/accumulated.
  - platform: template
    name: ${short_name} Total Watts Main
    id: totalWattsMain
    lambda: return id(L1Watts).state + id(L2Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}

#Total Amps Main
  - platform: template
    name: ${short_name} Total Amps Main
    id: totalAmpsMain
    lambda: return id(L1Amps).state + id(L2Amps).state ;
    accuracy_decimals: 1
    unit_of_measurement: A
    device_class: current
    update_interval: ${update_time}
```
