### DISCUSSION TITLE
Amps not updating as frequently with new add on board

### DISCUSSION THREAD

**Discussion by jbuszkie** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#173] [Q&A]
I just got a new Add in board as I was running out of slots.  I'm measuring the current and power for my heat pumps.  Heat pump 1 is on the older add in board and updates like I expect it to.  The new one, however.. doesn't.  But the power does?
The lack of points is making my Grafana graph not correct..

Here are the two heat pump with points enabled.
![image](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/11888706/f722b98c-21bb-4362-9837-448bdf462a7f)
And here is the power:
![image](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/11888706/d49175d1-a1d5-444e-9ce6-a5de81e51644)

Clearly the update interval should be the same for power and amps, right?  Why are the amps not updating as frequently?
Here is the code snippet for the new add in board. 
```
 - platform: atm90e32
    cs_pin: 27
    phase_a:
      voltage:
        name: ${disp_name} ${add_2} Volts A
        id: ${add_2}ic1Volts
        accuracy_decimals: 1
      current:
        name: ${disp_name} ${add_2} CT1 Amps
        id: ${add_2}ct1Amps
      power:
        name: ${disp_name} ${add_2} CT1 Power
      power_factor:
        name: ${disp_name} ${add_2} CT1 Power Factor
      gain_voltage: 5353
      gain_ct: 26291 #2/25/24
    phase_b:
      current:
        name: ${disp_name} ${add_2} CT2 Amps
        id: ${add_2}ct2Amps
      power:
        name: ${disp_name} ${add_2} CT2 Power
      gain_voltage: 5353
      gain_ct: 27752
    phase_c:
      current:
        name: ${disp_name} ${add_2} CT3 Amps
        id: ${add_2}ct3Amps
      gain_voltage: 5353
      gain_ct: 32498
    frequency:
      name: ${disp_name} ${add_2} Freq A
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}

```
