### DISCUSSION TITLE
Reading negative wants on house L2

### DISCUSSION THREAD

**Discussion by ideal2545** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#53] [Q&A]
Quick question, the way my box is wired it was really tight and I was able to get the clamps on but one is reading negative. I read the documentation that states the thing to do is to simply flip it over, but can I just account for this in the ESPHOME code, I dont want to mess with any subsequent formulas unless its okay to do so? 

Also as a education thing for me, I made sure to place both of the legs with both facing the same direction, when dealing with two phase (240v) should I always make sure one is facing the opposite way? 

p.s. I ended up just flipping over the clamps but I imagine I probably could have applied a filter. Thanks! Jon

**Comment by kgalilio** [comment]
In ESPHome you can try this:
```
    phase_a:
      voltage:
        name: ${disp_name} Volts A AO1
        id: ic1VoltsAO1
        accuracy_decimals: 1
      current:
        name: ${disp_name} CT7 Amps
        id: ct7Amps
      power:
        name: ${disp_name} CT7 Watts
        id: ct7Watts
        filters:
          - lambda: return abs(x);
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
```
