### DISCUSSION TITLE
Positive Amps, Negative Watts

### DISCUSSION THREAD

**Discussion by mick1988** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#87] [Q&A] [answered]
It's not on every sensor, but a few of my circuits have positive amps, but negative watts. Ive verified that the CTs are on the correct way. CT5 and CT6 are wired the exact same and CT5 is working correctly, but CT6 shows negative watts.

12C CT5 Amps | 9.52 A |  
12C CT5 Watts | 1075.88 W |  
12C CT6 Amps | 2.64 A |  
12C CT6 Watts | -287.50 W

```
    phase_b:
      current:
        name: ${disp_name} CT5 Amps
        id: ct5Amps
      power:
        name: ${disp_name} CT5 Watts
        id: ct5Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      current:
        name: ${disp_name} CT6 Amps
        id: ct6Amps
      power:
        name: ${disp_name} CT6 Watts
        id: ct6Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
```
I can "fix" it by adding:
```
        filters:
          - lambda: return abs(x);
```
But I'd like to know why some calculate correctly and others do not. Thanks!
