### DISCUSSION TITLE
Unable to get all 36 Clamps to report into HA

### DISCUSSION THREAD

**Discussion by mountainbiker54** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#95] [Q&A]
I'm trying to get each of the 36 clamps to report into homeassistant. The below code works, but if I try and add more than 17 inputs the esp just crashes with the below error. Any help would be appreciated.

Thanks

Working Code:

```
# Example config for when jp8-jp11 are all bridged - this connects all the voltage channels and allows for power to be calculated by the meter directly.
# Boards >= v1.4 jp8-jp11 are removed and have all voltage channels connected
# 1 add-on board

substitutions:
# Change the disp_name to something you want  
  disp_name: powermon
# Interval of how often the power is updated
  update_time: 10s
# Current Transformers:
#  20A/25mA SCT-006: 11143
#  30A/1V SCT-013-030: 8650
#  50A/1V SCT-013-050: 15420
#  80A/26.6mA SCT-010: 41660
#  100A/50ma SCT-013-000: 27518
#  120A/40mA: SCT-016: 41787
#  200A/100mA SCT-024: 27518
  current_cal: '27518'
# Jameco 9VAC Transformer: 
#  For meter versions: 
#  >= v1.3: 7305
#  <= v1.2: 42620
  voltage_cal: '7305'

esphome:
  name: powermon
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
# mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_user
#  password: !secret mqtt_pass

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "697f9126c4101854dbd1f39ff026ea9c"
  
web_server:
  port: 80

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23
sensor:
#IC1 Main
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${disp_name} Volts A Main
        id: ic1Volts
        accuracy_decimals: 1
      power:
        name: ${disp_name} CT1 Watts 
        id: ct1Watts
        accuracy_decimals: 1
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:
      power:
        name: ${disp_name} CT2 Watts 
        id: ct2Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      power:
        name: ${disp_name} CT3 Watts
        id: ct3Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    frequency:
      name: ${disp_name} Freq A Main
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 Main
  - platform: atm90e32
    cs_pin: 4
    phase_a:
      power:
        name: ${disp_name} CT4 Watts 
        id: ct4Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:
      power:
        name: ${disp_name} CT5 Watts 
        id: ct5Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      power:
        name: ${disp_name} CT6 Watts 
        id: ct6Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC1 AddOn 1
  - platform: atm90e32
    cs_pin: 0
    phase_a:  
      power:
        name: ${disp_name} CT7 Watts
        id: ct7Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b: 
      power:
        name: ${disp_name} CT8 Watts
        id: ct8Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      power:
        name: ${disp_name} CT9 Watts
        id: ct9Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 AddOn 1
  - platform: atm90e32
    cs_pin: 16
    phase_a:  
      power:
        name: ${disp_name} CT10 Watts
        id: ct10Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:  
      power:
        name: ${disp_name} CT11 Watts
        id: ct11Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:  
      power:
        name: ${disp_name} CT12 Watts
        id: ct12Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC1 AddOn 2
  - platform: atm90e32
    cs_pin: 27
    phase_a:  
      power:
        name: ${disp_name} CT13 Watts
        id: ct13Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:   
      power:
        name: ${disp_name} CT14 Watts
        id: ct14Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:    
      power:
        name: ${disp_name} CT15 Watts
        id: ct15Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 AddOn 2
  - platform: atm90e32
    cs_pin: 17
    phase_a:    
      power:
        name: ${disp_name} CT16 Watts
        id: ct16Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:
      power:
        name: ${disp_name} CT17 Watts
        id: ct17Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      power:
        name: ${disp_name} CT18 Watts
        id: ct18Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC1 AddOn 3
  - platform: atm90e32
#do not use GPIO2 if ESP32 has an on-board LED assigned to it
    cs_pin: 2
    phase_a:  
      power:
        name: ${disp_name} CT19 Watts
        id: ct19Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:    
      power:
        name: ${disp_name} CT20 Watts
        id: ct20Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:  
      power:
        name: ${disp_name} CT21 Watts
        id: ct21Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 AddOn 3
  - platform: atm90e32
    cs_pin: 21
    phase_a:     
      power:
        name: ${disp_name} CT22 Watts
        id: ct22Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:   
      power:
        name: ${disp_name} CT23 Watts
        id: ct23Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:    
      power:
        name: ${disp_name} CT24 Watts
        id: ct24Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC1 AddOn 4
  - platform: atm90e32
    cs_pin: 13
    phase_a:      
      power:
        name: ${disp_name} CT25 Watts
        id: ct25Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:     
      power:
        name: ${disp_name} CT26 Watts
        id: ct26Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:     
      power:
        name: ${disp_name} CT27 Watts
        id: ct27Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 AddOn 4
  - platform: atm90e32
    cs_pin: 22
    phase_a:     
      power:
        name: ${disp_name} CT28 Watts
        id: ct28Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:     
      power:
        name: ${disp_name} CT29 Watts
        id: ct29Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:      
      power:
        name: ${disp_name} CT30 Watts
        id: ct30Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC1 AddOn 5
  - platform: atm90e32
    cs_pin: 14
    phase_a:      
      power:
        name: ${disp_name} CT31 Watts
        id: ct31Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:     
      power:
        name: ${disp_name} CT32 Watts
        id: ct32Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:    
      power:
        name: ${disp_name} CT33 Watts
        id: ct33Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
#IC2 AddOn 5
  - platform: atm90e32
    cs_pin: 25
    phase_a:    
      power:
        name: ${disp_name} CT34 Watts
        id: ct34Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_b:   
      power:
        name: ${disp_name} CT35 Watts
        id: ct35Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:  
      power:
        name: ${disp_name} CT36 Watts
        id: ct36Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}

#Total Watts Main
  - platform: template
    name: ${disp_name} Total Watts Main
    id: totalWattsMain
    lambda: return id(ct1Watts).state + id(ct2Watts).state + id(ct3Watts).state + id(ct4Watts).state + id(ct5Watts).state + id(ct6Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts AddOn1
  - platform: template
    name: ${disp_name} Total Watts Add-on1
    id: totalWattsAddOn1
    lambda: return id(ct7Watts).state + id(ct8Watts).state + id(ct9Watts).state + id(ct10Watts).state + id(ct11Watts).state + id(ct12Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts AddOn2
  - platform: template
    name: ${disp_name} Total Watts Add-on2
    id: totalWattsAddOn2
    lambda: return id(ct13Watts).state + id(ct14Watts).state + id(ct15Watts).state + id(ct16Watts).state + id(ct17Watts).state + id(ct18Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts AddOn3
  - platform: template
    name: ${disp_name} Total Watts Add-on3
    id: totalWattsAddOn3
    lambda: return id(ct19Watts).state + id(ct20Watts).state + id(ct21Watts).state + id(ct22Watts).state + id(ct23Watts).state + id(ct24Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts AddOn4
  - platform: template
    name: ${disp_name} Total Watts Add-on4
    id: totalWattsAddOn4
    lambda: return id(ct25Watts).state + id(ct26Watts).state + id(ct27Watts).state + id(ct28Watts).state + id(ct29Watts).state + id(ct30Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts AddOn5
  - platform: template
    name: ${disp_name} Total Watts Add-on5
    id: totalWattsAddOn5
    lambda: return id(ct31Watts).state + id(ct32Watts).state + id(ct33Watts).state + id(ct34Watts).state + id(ct35Watts).state + id(ct36Watts).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#Total Watts
  - platform: template
    name: ${disp_name} Total Watts
    id: totalWatts
    lambda: return id(totalWattsMain).state + id(totalWattsAddOn1).state + id(totalWattsAddOn2).state + id(totalWattsAddOn3).state + id(totalWattsAddOn4).state + id(totalWattsAddOn5).state ;
    accuracy_decimals: 1
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
#kWh
  - platform: total_daily_energy
    name: ${disp_name} Total kWh
    power_id: totalWatts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing

  - platform: total_daily_energy
    name: ${disp_name} Num1Test kWh
    power_id: ct1Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${disp_name} Num2Test kWh
    power_id: ct2Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num3Test kWh
    power_id: ct3Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh    
  - platform: total_daily_energy
    name: ${disp_name} Num4Test kWh
    power_id: ct4Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${disp_name} Num5Test kWh
    power_id: ct5Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num6Test kWh
    power_id: ct6Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh      

  - platform: total_daily_energy
    name: ${disp_name} Num7Test kWh
    power_id: ct7Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${disp_name} Num8Test kWh
    power_id: ct8Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num9Test kWh
    power_id: ct9Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh  
  - platform: total_daily_energy
    name: ${disp_name} Num10Test kWh
    power_id: ct10Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${disp_name} Num11Test kWh
    power_id: ct11Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num12Test kWh
    power_id: ct12Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh  
  - platform: total_daily_energy
    name: ${disp_name} Num13Test kWh
    power_id: ct13Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${disp_name} Num14Test kWh
    power_id: ct14Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num15Test kWh
    power_id: ct15Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh  
  - platform: total_daily_energy
    name: ${disp_name} Num16Test kWh
    power_id: ct16Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${disp_name} Num17Test kWh
    power_id: ct17Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
 
            
time:
  - platform: sntp
    id: sntp_time


```
Error:
```
[11:44:18]ets Jun  8 2016 00:22:57
[11:44:18]
[11:44:19]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[11:44:19]configsip: 0, SPIWP:0xee
[11:44:19]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[11:44:19]mode:DIO, clock div:2
[11:44:19]load:0x3fff0018,len:4
[11:44:19]load:0x3fff001c,len:1044
[11:44:19]load:0x40078000,len:8896
[11:44:19]load:0x40080400,len:5828
[11:44:19]entry 0x400806ac
[11:44:19]Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
[11:44:19]Debug exception reason: Stack canary watchpoint triggered (loopTask) 
[11:44:19]Core 1 register dump:
[11:44:20]PC      : 0x401129e6  PS      : 0x00060736  A0      : 0x8011688d  A1      : 0x3ffb0060  
[11:44:20]A2      : 0x3ffb0070  A3      : 0x3f4019c9  A4      : 0x00000001  A5      : 0x00000018  
[11:44:20]A6      : 0x00000000  A7      : 0x0000000c  A8      : 0x3ffb0070  A9      : 0x3ffb0070  
[11:44:20]A10     : 0x3ffb0070  A11     : 0x0000002a  A12     : 0xffffffff  A13     : 0x3f40b308  
[11:44:20]A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x0000001f  EXCCAUSE: 0x00000001  
[11:44:21]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
[11:44:21]
[11:44:21]ELF file SHA256: 0000000000000000
[11:44:21]
[11:44:21]Backtrace: 0x401129e6:0x3ffb0060 0x4011688a:0x3ffb0370 0x401168c6:0x3ffb0400 0x400d8985:0x3ffb0440 0x400d89b9:0x3ffb0470 0x400d89ed:0x3ffb04c0 0x400d8bad:0x3ffb04e0 0x400e13fd:0x3ffb0500 0x400e142a:0x3ffb0530 0x400d8b5d:0x3ffb0590 0x400e248e:0x3ffb05c0 0x400f4f3e:0x3ffb1fb0 0x40089c1e:0x3ffb1fd0
[11:44:21]
[11:44:21]Rebooting...
```
