### ISSUE TITLE
Communication with ATM90E32 failed

### ISSUE THREAD

**Issue by max-rousseau** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#111]
Hello - I recently picked up a v1.4 rev1 board (the black one). As I was trying, unsuccessfully so, to calculate the right calibration values on a small test circuit I have (just one light bulb) the board eventually started to say that the communication failed with the sensors. I did swap them out as I was trying to figure the right calibration between all 6 plugs, to see if the measurements were the same.

To simplify I now just power it with usb power and have only one sensor in CT1. Still no dice.

> INFO OTA successful
> INFO Successfully uploaded program.
> INFO Starting log output from 192.168.xx using esphome API
> INFO Successfully connected to 192.168.xx
> [07:54:37][I][app:102]: ESPHome version 2022.8.0 compiled on Aug 23 2022, 07:53:54
> [07:54:37][C][wifi:491]: WiFi:
> [07:54:37][C][wifi:353]:   Local MAC: 24:0A:C4:58:E4:54
> [07:54:37][C][wifi:354]:   SSID: [redacted]
> [07:54:37][C][wifi:355]:   IP Address: 192.168.xx
> [07:54:37][C][wifi:357]:   BSSID: [redacted]
> [07:54:37][C][wifi:358]:   Hostname: 'edison'
> [07:54:37][C][wifi:360]:   Signal strength: -46 dB ▂▄▆█
> [07:54:37][C][wifi:364]:   Channel: 1
> [07:54:37][C][wifi:365]:   Subnet: 255.255.255.0
> [07:54:37][C][wifi:366]:   Gateway: 192.168.30.1
> [07:54:37][C][wifi:367]:   DNS1: 0.0.0.0
> [07:54:37][C][wifi:368]:   DNS2: 0.0.0.0
> [07:54:37][C][logger:275]: Logger:
> [07:54:37][C][logger:276]:   Level: DEBUG
> [07:54:37][C][logger:277]:   Log Baud Rate: 115200
> [07:54:37][C][logger:278]:   Hardware UART: UART0
> [07:54:37][C][spi:097]: SPI bus:
> [07:54:37][C][spi:098]:   CLK Pin: GPIO18
> [07:54:37][C][spi:099]:   MISO Pin: GPIO19
> [07:54:37][C][spi:100]:   MOSI Pin: GPIO23
> [07:54:37][C][spi:102]:   Using HW SPI: YES
> [07:54:37][C][:129]: ATM90E32:
> [07:54:37][C][atm90e32:130]:   CS Pin: GPIO5
> [07:54:37][E][atm90e32:132]: Communication with ATM90E32 failed!
> [07:54:37][C][atm90e32:134]:   Update Interval: 10.0s
> [07:54:37][C][atm90e32:135]:   Voltage A '6C Volts A'
> [07:54:37][C][atm90e32:135]:     Device Class: 'voltage'
> [07:54:37][C][atm90e32:135]:     State Class: 'measurement'
> [07:54:37][C][atm90e32:135]:     Unit of Measurement: 'V'
> [07:54:37][C][atm90e32:135]:     Accuracy Decimals: 1
> [07:54:37][C][atm90e32:136]:   Current A '6C CT1 Amps'
> [07:54:37][C][atm90e32:136]:     Device Class: 'current'
> [07:54:37][C][atm90e32:136]:     State Class: 'measurement'
> [07:54:37][C][atm90e32:136]:     Unit of Measurement: 'A'
> [07:54:37][C][atm90e32:136]:     Accuracy Decimals: 2
> [07:54:37][C][atm90e32:137]:   Power A '6C CT1 Watts'
> [07:54:37][C][atm90e32:137]:     Device Class: 'power'
> [07:54:37][C][atm90e32:137]:     State Class: 'measurement'
> [07:54:37][C][atm90e32:137]:     Unit of Measurement: 'W'
> [07:54:37][C][atm90e32:137]:     Accuracy Decimals: 2
> [07:54:37][C][atm90e32:156]:   Frequency '6C Freq A'
> [07:54:37][C][atm90e32:156]:     State Class: 'measurement'
> [07:54:37][C][atm90e32:156]:     Unit of Measurement: 'Hz'
> [07:54:37][C][atm90e32:156]:     Accuracy Decimals: 1
> [07:54:37][C][atm90e32:156]:     Icon: 'mdi:current-ac'

**Comment by CircuitSetup** [comment]
Hi Max - can you provide your config file? Also, what ESP32 are you using?

**Comment by max-rousseau** [comment]
Of course, sorry for not including initially. Pretty vanilla. The board I am using now is Esprsesif ESP32-WROOM-32D. I think this one's a bit older I could try with another one but didn't dig deeper on that front given at least initially it was working.

```
substitutions:
  disp_name: 6C
  update_time: 10s
  current_cal: '26275' # gain_ct # old 27961
  voltage_cal: '15970' # gain_voltage # old '15970'

esphome:
  name: Foo

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # level: VERY_VERBOSE
  
# Enable Home Assistant API
api:
  encryption:
    key: "[redacted]"

ota:
  password: "[redacted]"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.[redacted]
    gateway: 192.168.[redacted]
    subnet: 255.255.255.0

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:

  - platform: wifi_signal
    name: ${disp_name} WiFi
    update_interval: 60s

  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${disp_name} Volts A
        id: ic1Volts
        accuracy_decimals: 1
      current:
        name: ${disp_name} CT1 Amps
        id: ct1Amps
      power:
        name: ${disp_name} CT1 Watts
        id: ct1Watts
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}

    frequency:
      name: ${disp_name} Freq A
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}

```
