### ISSUE TITLE
Second Voltage and Frequency Reading Zero?

### ISSUE THREAD

**Issue by ClintElliotMalcolm** [CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter#156]
I'm trying to use ESPHome with CircuitSetup to measure my whole home energy use. However, I'm not able to get frequency or voltage on the second phase of my Main Input Power to the breaker. I'm in the US and working on a 100 Amp daughter breaker box. I'm using a secondary voltage reading on the other phase and I believe I followed all the steps to use it correctly, but obviously something isn't working. 

Values read for my main input:
![image](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/0223b9da-300b-4aee-8f7c-b2bafa90e87c)
 
Code:
```
substitutions:
# Change the disp_name to something you want  
  disp_name: Main House Energy
# Interval of how often the power is updated
  update_time: 10s
  voltage_cal: '7305'
  a20_cal: '11143'
  a30_cal: '8650'
  a100_cal: '27518'

esphome:
  name: main-house-energy-monitor
  friendly_name: main-house-energy-monitor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
    
# Current Transformers:
#  20A/25mA SCT-006: 11143
#  30A/1V SCT-013-030: 8650
#  50A/1V SCT-013-050: 15420
#  50A/16.6mA SCT-010: 41334
#  80A/26.6mA SCT-010: 41660
#  100A/50ma SCT-013-000: 27518
#  120A/40mA: SCT-016: 41787
#  200A/100mA SCT-024: 27518
#  200A/50mA SCT-024: 55036

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:
  - platform: wifi_signal
    name: ${disp_name} WiFi
    update_interval: 60s
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: Main In Phase A Volts
        id: ic1Volts
        accuracy_decimals: 1
      current:
        name: Main In Phase A Amps
        id: ct1Amps
      power:
        name: Main In Phase A Watts
        id: ct1Watts
      forward_active_energy:
        name:  Main In Phase A FAWattHours
        id: ct1FAWattHours
      reactive_power:
        name:  Main In Phase A Reactive Power
        id: ct1ReactivePower
      power_factor:
        name:  Main In Phase A Power Factor
        id: ct1PowerFactor
      gain_voltage: ${voltage_cal}
      gain_ct: ${a100_cal}
    frequency:
      name: ${disp_name} Freq A
    line_frequency: 60Hz
    gain_pga: 2X
    update_interval: ${update_time}
  - platform: atm90e32
    cs_pin: 4
    phase_a:
      voltage:
        name: Main In Phase B Volts
        id: ic2Volts
        accuracy_decimals: 1
      current:
        name: Main In Phase B Amps
        id: ct6Amps
      power:
        name: Main In Phase B Watts
        id: ct6Watts
      forward_active_energy:
        name:  Main In Phase B FAWattHours
        id: ct6FAWattHours
      reactive_power:
        name:  Main In Phase B Reactive Power
        id: ct6ReactivePower
      power_factor:
        name:  Main In Phase B Power Factor
        id: ct6PowerFactor
      gain_voltage: ${voltage_cal}
      gain_ct: ${a100_cal}
    frequency:
      name: ${disp_name} Freq B
    line_frequency: 60Hz
    gain_pga: 2X
    update_interval: ${update_time}
  - platform: atm90e32
    cs_pin: 5
    phase_b:
      current:
        name: Main and Up Bath GFI Amps
        id: ct2Amps
      power:
        name: Main and Up Bath GFI Watts
        id: ct2Watts
      forward_active_energy:
        name: Main and Up Bath GFI FAWattHours
        id: ct2FAWattHours
      reactive_power:
        name: Main and Up Bath GFI Reactive Power
        id: ct2ReactivePower
      power_factor:
        name: Main and Up Bath GFI Power Factor
        id: ct2PowerFactor
      gain_voltage: ${voltage_cal}
      gain_ct: ${a20_cal}
    phase_c:
      current:
        name: Dishwasher Amps
        id: ct3Amps
      gain_voltage: ${voltage_cal}
      gain_ct: ${a20_cal} 
      power:
        name: Dishwasher Watts
        id: ct3Watts
      forward_active_energy:
        name: Dishwasher FAWattHours
        id: ct3FAWattHours
      reactive_power:
        name: Dishwasher Reactive Power
        id: ct3ReactivePower
      power_factor:
        name: Dishwasher Power Factor
        id: ct3PowerFactor
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: atm90e32
    cs_pin: 4
    phase_c:
      current:
        name: Disposal Amps
        id: ct4Amps
      gain_voltage: ${voltage_cal}
      gain_ct: ${a20_cal}
      power:
        name: Disposal Watts
        id: ct4Watts
      forward_active_energy:
        name: Disposal FAWattHours
        id: ct4FAWattHours
      reactive_power:
        name: Disposal Reactive Power
        id: ct4ReactivePower
      power_factor:
        name: Disposal Power Factor
        id: ct4PowerFactor
    phase_b:
      current:
        name: Heater P Fan Amps
        id: ct5Amps
      gain_voltage: ${voltage_cal}
      gain_ct: ${a20_cal}
      power:
        name: Heater P Fan Watts
        id: ct5Watts
      forward_active_energy:
        name: Heater P Fan FAWattHours
        id: ct5FAWattHours
      reactive_power:
        name: Heater P Fan Reactive Power
        id: ct5ReactivePower
      power_factor:
        name: Heater P Fan Power Factor
        id: ct5PowerFactor
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
```
 
Severed J12 and J13:
![PXL_20230910_193446950](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/32060d70-8d46-46d0-a48a-d9b7850268ba)

My admittedly terrible soldering job of adding the second voltage reference:
![PXL_20230910_192827047 MP](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/f3ce7a3a-a8cb-4700-8afb-4d761231d4ff)

Using two Jameco AC 120V 60 Hz to AC 9 Volt adapters on two plugs on different phases:
![PXL_20230910_192804114](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/1c7884b3-78f8-48fd-bf25-9111cc023132)

Potentially Relevant Other Photos:
![PXL_20230910_192742062](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/46a7f42a-c98c-47de-bddc-7407fae29d63)
![PXL_20230910_192747042](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/ea420391-ec68-413d-871a-ebc6767b6ddb)
![PXL_20230910_192750952](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/4aaa5056-137d-4553-92d9-a0a4ab57a16c)
![PXL_20230910_192753634](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/79b1f82a-ad92-44d9-8c2f-d2f22efdee69)
![PXL_20230910_192814782](https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/assets/2604394/c37e35bd-c373-498d-b66b-7786cc566f0e)
